version: '3.7'
services:
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - 8761:8761
  eureka-server-client:
    build: ./eureka-server-client
    container_name: eureka-server-client
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka/
    ports:
      - 8081:8080
  eureka-server-feign-client:
    build: ./eureka-server-feign-client
    container_name: eureka-server-feign-client
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka/
    ports:
      - 8082:8080
  eureka-server-client-svc:
    build: ./eureka-server-client-svc
    container_name: eureka-server-client-svc
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka/
    ports:
      - 8083:8080
